### ISSUE TITLE
Az artifacts universal download failed

### ISSUE THREAD

**Issue by udossOpenValue** [Azure/azure-cli-extensions#1018]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Description of issue `An error occurred on the service. A potentially dangerous Request.Path value was detected from the client (:)``

I have a colon in my package name and when I run the command , I got this message
`An error occurred on the service. A potentially dangerous Request.Path value was detected from the client (:)`

Can you have a look?
Regards
-----

**Comment by yonzhan** [comment]
Was this issue related to Azure CLI or Azure CLI extensions ?

**Comment by ishitam8** [comment]
Hi @udossOpenValue  ,

What type of package are you trying to download ? Is it a universal package?
Since, they can't contain colon in their names.
Refer Azure/azure-devops-cli-extension#806.

If you are still facing the issue, kindly raise a bug in this repo : https://github.com/Azure/azure-devops-cli-extension/

**Comment by atbagga** [comment]
Closing this issue as per above comment.
Please feel free to file an issue in the extension repo -  https://github.com/Azure/azure-devops-cli-extension if required.
