### ISSUE TITLE
We need release pipeline for extensions

### ISSUE THREAD

**Issue by zikalino** [Azure/azure-cli-extensions#1028]
We should have something similar to Python SDK release:

(1) make sure prerelease ci tests are complete, so we know everything is ready, no more issues

(2) Release pipeline that:
- takes build wheel and pushes it to extension artifacts storage
- creates / updates index.json --- this process should end with PR containing changes in index.json, or even just merging update to index.json automatically

**Comment by haroldrandom** [comment]
Will make a plan after Ignite. 😃

**Comment by Juliehzl** [comment]
Both are good. If for (2) we can make sure the tests for build are complete, I will vote for (2). For my previous PR without updating index.json, it can pass CI but actually it shouldn't because there are something wrong and it looks it doesn't run all my test scenarios. But for the PR with index.json, it test many things although there are some other annoying things...

**Comment by peizhou298** [comment]
This pipeline is good, but I wonder if it is possible to swap step (1) and (2).1, because PR with index.json seems have more CI tests than PR without,  which in my understanding is if I passed the first CI test but failed in second, I need to reproduce the whole process.  Even if everything works well, I also need to run CI test twice rather once...

**Comment by haroldrandom** [comment]
> Both are good. If for (2) we can make sure the tests for build are complete, I will vote for (2). For my previous PR without updating index.json, it can pass CI but actually it shouldn't because there are something wrong and it looks it doesn't run all my test scenarios. But for the PR with index.json, it test many things although there are some other annoying things...

referenced #1067
