### ISSUE TITLE
No documentation on how to install specific version of an extension.

### ISSUE THREAD

**Issue by ggorman** [Azure/azure-cli-extensions#1123]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
Any (specifically experienced for image-copy-extension)

### Description of issue (in as much detail as possible)

Some issue responses advise using a specific version number of an extension (eg #979). However, az extension does not include document any way to specify a version number.

-----

**Comment by haroldrandom** [comment]
As far as I know, currently, extensions don't have the ability to install by specific version.

**Comment by ggorman** [comment]
The following command at least allows one to use the pre-release version of an extension. Good when a patch is required.
`pip install --upgrade --target ~/.azure/cliextensions/image-copy-extension "git+https://github.com/Azure/azure-cli-extensions.git#subdirectory=src/image-copy&egg=image-copy-extension"`

**Comment by fengzhou-msft** [comment]
@ggorman Currently we don't have production support for installing previous extension version. But you can install through `--source` option. image-copy-extension is a good example since it's published on [pypi](https://pypi.org/project/image-copy-extension/#history). You can get the download link for any previous versions on pypi. Then run `az extension add --source https://download/link/to/specific/version/wheel/file.whl`. 

Most extension wheel files are stored in storage account. In our [index.json](https://github.com/Azure/azure-cli-extensions/blob/master/src/index.json), some extensions already listed the downloadUrl for multiple versions such as [storage_preview](https://github.com/Azure/azure-cli-extensions/blob/1ced093278f6d2edd53ccdbeda90a44bfb2208b5/src/index.json#L2470). For those that only shows the latest version, you can use the following hack taking netappfiles-preview as an example:
1. check the current download url in [index.json](https://github.com/Azure/azure-cli-extensions/blob/1ced093278f6d2edd53ccdbeda90a44bfb2208b5/src/index.json#L2054).
2. check the [History.rst](https://github.com/Azure/azure-cli-extensions/blob/1ced093278f6d2edd53ccdbeda90a44bfb2208b5/src/netappfiles-preview/HISTORY.rst) file for previous versions.
3. Replace the version you need in the current download url, for instance you want 0.3.0, the link becomes https://anfclipython.blob.core.windows.net/cli-extensions/netappfiles_preview-0.3.0-py2.py3-none-any.whl
4. Install with `az extension add --source https://anfclipython.blob.core.windows.net/cli-extensions/netappfiles_preview-0.3.0-py2.py3-none-any.whl`.

This hack is not guaranteed to work for all extensions since they are maintained by different teams. They have the liberty to store the wheel file in any different public locations for each verison.

We may consider adding production support for installing specific extension version in the future.
