### ISSUE TITLE
There is no such a command in Azure CLI

### ISSUE THREAD

**Issue by hihorika** [Azure/azure-cli-extensions#1213]
It should be `az webapp create-remote-connection`

I checked about v2.0.78 (cloud shell) and v2.0.80 (local PC).

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 04a67a6a-b2b8-ed24-bb78-e9773fef6d86
* Version Independent ID: beeae428-5c77-4501-0ab5-a7301971f058
* Content: [az webapp remote-connection](https://docs.microsoft.com/ja-jp/cli/azure/ext/webapp/webapp/remote-connection?view=azure-cli-latest#feedback)
* Content Source: [latest/docs-ref-autogen/ext/webapp/webapp/remote-connection.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/webapp/webapp/remote-connection.yml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by hihorika** [comment]
According to this discussion, it was renamed to `create-remote-connection`, but it isn't reflected to the document.

**Comment by navba-MSFT** [comment]
@hihorika Apologies for the late reply. [Here](https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-create-remote-connection) is the documentation which talks about the remote connection. Hope this helps. Also this issue is open for quite sometime, please let us know if you need any further help on this. Awaiting your reply.

**Comment by panchagnula** [comment]
This is the document that talks abt this command https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-create-remote-connection , this is on core-cli so make sure you are not using the extension.
