### ISSUE TITLE
spaces in foldername, storage-preview extension issue

### ISSUE THREAD

**Issue by gitsathish** [Azure/azure-cli-extensions#1277]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
storage-preview

### Description of issue (in as much detail as possible)
az storage blob directory move
is not able to handle foldernames with spaces in them. enclosing with single or double quotes does not help.
if we are using folder names with spaces to the -s or -d arguments to az storage blob directory move, it comes back with a "az storage blob directory move: error: The specified blob does not exist. ErrorCode: BlobNotFound" message.

-----

**Comment by yungezz** [comment]
HI @Juliehzl  could you pls have a look? thanks.

**Comment by yonzhan** [comment]
add to S167.

**Comment by zhoxing-ms** [comment]
`PUT https://{account_name}.dfs.core.windows.net/{container_name}/{destination_path}?mode=posix`
When calling the above Service to update the directory in a Container, the following error occurs:
> HTTP status code=400, Exception=The source URI is invalid. ErrorCode: InvalidSourceUri{"error":{"code":"InvalidSourceUri","message":"The source URI is invalid.\nRequestId:0231a6e2-401f-000d-38fb-160a8f000000\nTime:2020-04-20T10:10:39.8936743Z"}}.

The operation to update the directory name on the portal is successful, and the requested Service is consistent with the CLI, but the encoding of `x-ms-rename-source` in the Header is inconsistent
In CLI:
`x-ms-rename-source:/{container_name}/source space`
In portal:
`x-ms-rename-source:%2F{container_name}%2Fsource%20path`

It seems that this problem may be caused by the `x-ms-rename-source` is not encoded in Python SDK, so we need the Service team to help us check it out~

**Comment by zhoxing-ms** [comment]
I have submitted a PR that adding the encoding logic of `x-ms-rename-source` in CLI at first
