### ISSUE TITLE
az iot hub device-identity list   the hub is NOT an optional parameter

### ISSUE THREAD

**Issue by djaus2** [Azure/azure-cli-extensions#1331]
```
PS&gt; az iot hub device-identity list
Please provide an IoT Hub entity name (via the '--hub-name' or '-n' parameter) or IoT Hub connection string via --login...
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62c92565-2490-7306-fa08-b16aa2a402a6
* Version Independent ID: 73f40753-0f05-7e45-ca7d-f0a9d2a276ce
* Content: [az iot hub device-identity](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/hub/device-identity?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-hub-device-identity-list)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub/device-identity.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub/device-identity.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
iot hub

**Comment by jlian** [comment]
@digimaun would know know about this?

**Comment by digimaun** [comment]
This behavior is by design for most of the IoT Hub based commands in the IoT extension. The reason is these type of commands support either AAD **OR** connection string based login.

So you need to provide **either** your target IoT Hub name via `--hub-name`/`-n` (if you have already run "az login")  OR a iothub connection string via `--login` that has the permission to execute the desired operation.

**Comment by jlian** [comment]
Thanks for the explanation! @djaus2 feel free to reopen the issue if you still have questions.
