### ISSUE TITLE
az monitor log-analytics solution create  - remove Remove --plan-publisher and --plan-product

### ISSUE THREAD

**Issue by dougbrad** [Azure/azure-cli-extensions#1677]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)

az monitor log-analytics solution create 

### Description of issue (in as much detail as possible)

Remove --plan-publisher and --plan-product
Remove any mention to Microsoft or 3rd party solutions - this is for Microsoft solutions only.

-----

**Comment by yonzhan** [comment]
add to S170

**Comment by zhoxing-ms** [comment]
@dougbrad Thanks for your feedback, I will annotate `--plan-publisher`, `--name` and `--plan-product` with `deprecate_info`, add a new parameter `--solution-type` and remove any mention to Microsoft or 3rd party solutions.
Since the solution does not modify the logic of any old parameters, they are only declared to be deleted temporarily and will be deleted when the customers no longer uses them, so there will be no breaking change.
