### ISSUE TITLE
CMK Az CLI Property id is invalid error

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-cli-extensions#1826]
- If the issue is to do with Azure CLI 2.0 in-particular, create an issue here at [Azure/azure-cli](https://github.com/Azure/azure-cli/issues)

### Extension name (the extension in question)
databricks

### Description of issue (in as much detail as possible)
https://msdata.visualstudio.com/Azure%20Databricks/_workitems/edit/771294
-----
All update operations are blocked in Az CLI
An error occurs when running the following commands:
az databricks workspace update --resource-group NEWWSAIRG --name ADB_6_4_348 --prepare-encryption
 az databricks workspace update --resource-group NEWWSAIRG --name ADB_6_4_348 --key-source Microsoft.Keyvault --key-vault https://keybyok357.vault.azure.net/ --key-name key357 --key-version 78208845c7574d59880dc75eac06666

Error:
LinkedInvalidPropertyId - Property id '' at path 'properties.parameters.customVirtualNetworkId.value' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.

**Comment by yungezz** [comment]
HI @fengzhou-msft could you pls look at it? It seems user error, anyway let's make intuitive doc.

**Comment by fengzhou-msft** [comment]
It seems service has made the chage to add this check. In update command, we need to first get then call create_or_update. It's caused by service returning 
```
"customVirtualNetworkId": {
      "type": "String",
      "value": ""
    }
```
in get response when we pass None for customVirtualNetworkId in request.
Please either fix the get response or support update `prepare-encryption` and other key properties in a patch request.
