### ISSUE TITLE
purge a specific front end domain

### ISSUE THREAD

**Issue by arsnyder16** [Azure/azure-cli-extensions#1918]
Is it possible to purge content from a front end

Based on the front door example if i have  `images.contoso.com` and `videos.contoso.com` and i want to purge just `images.contoso.com` 

Is that possible?
Based on the docs it all seems to be relative paths. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1b5ddd-0054-0175-b689-d20a1349bedb
* Version Independent ID: 72ccc1b6-814f-b780-99cd-ab48dfdecb66
* Content: [az network front-door](https://docs.microsoft.com/en-us/cli/azure/ext/front-door/network/front-door?view=azure-cli-latest#ext-front-door-az-network-front-door-purge-endpoint)
* Content Source: [latest/docs-ref-autogen/ext/front-door/network/front-door.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/front-door/network/front-door.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
add to S173

**Comment by MyronFanQiu** [comment]
@arsnyder16 Hi. Sorry for the delay. I think you can just delete one front end.

**Comment by MyronFanQiu** [comment]
@arsnyder16 Hi, Are you still meeting this issue?

**Comment by arsnyder16** [comment]
@MyronFanQiu Yes i don't see a way to do this can you be more specific on how to purge the cache of a specific domain. I heard from other another issues that this wasn't possible so i am curious on how you suggest we can do this

**Comment by MyronFanQiu** [comment]
@arsnyder16 Let me dig into it and confirm with service team to see whether we can do it or not. I might misunderstand your requirement. Sorry about that.

**Comment by MyronFanQiu** [comment]
@MoustafaEid Hey. Could you please help take a look? I'm not sure whether this is a service limitation or CLI should do something.

**Comment by MyronFanQiu** [comment]
After some learning I think I understand your feature request. Let me clarify it in my way and please correct me if I misunderstand something.
- Front Door can have several frontend endpoint.
- Front Door can purge cache for a front door.
- Is there a way to purge cache for a frontend endpoint instead of the whole front door?

It seems like we cannot do that right now. We cannot do it through Portal as well. I cannot image the behind motivation for this feature request. Could you share more context? Meanwhile, I would invite service team to investigate this issue since they don't support it right now.

**Comment by tiny-dancer** [comment]
> I cannot image the behind motivation for this feature request. Could you share more context?

@MyronFanQiu one motivation that conceptually applies to a myriad of caching use-cases:

Single Front Door Front Ends:

- app1.domain.com
- app2.domain.com
- app3.domain.com
- appN.domain.com

These are N applications managed by N different teams and deployed by N distinct pipelines.  When a deployment occurs for a single app, there is a need to purge the app specific `index.html` for the updated static assets to be pulled.  Because each app hosts it's website on the cname root path.  When purging '/' for an app1 deployment, every other app is also purged.  This increases risk b/c each app's deployment impacts every other application, depending on the release cadence (several times a day to production for each application) and architectural complexity behind the cache.  This can have dramatic effects on the benefits of caching.

**Comment by t-bzhan** [comment]
Hi @[arsnyder16](https://github.com/arsnyder16), can you try out our  new Azure Front Door tiers—[Azure Front Door Standard and Premium](https://azure.microsoft.com/en-us/blog/introducing-the-new-azure-front-door-reimagined-for-modern-apps-and-content/), it allows the purge on domain level.
