### ISSUE TITLE
[Proposal] Support extension aliases

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-cli-extensions#24]
Consider adding support for extension aliases.

Currently, CI verifies that the name in the index matches the name of the extension as defined by the .whl file.

Tracking https://github.com/Azure/azure-cli/issues/5130

**Comment by digimaun** [comment]
This is a great idea.

**Comment by tamirkamara** [comment]
I would also like to see this move forward and make the extension names more user friendly... due to the issue where publishing to pypi (for instance) means that the name is long and not intuitive. 

As to the actual implementation:
1. add an alias property to the extension meta data
2. use the alias along with the name in the verification test script. How? will it first check if the name match and if not, check if the alias match
3. maybe add the alias to the print out in azure cli (extension list -o table)
4. How extension add will be - will it still use just the name of the extension or will maybe if it doesn't find it will look for the alias?
