### ISSUE TITLE
The page should include instructions on how to install this extension

### ISSUE THREAD

**Issue by tomstyles** [Azure/azure-cli-extensions#2458]
Out of the box, az does not support this extension, yet there is no mention of how to install it in this documentation.  

**Suggested text** 
These commands are only available in the app-insights extension. To install the extension run this command 

`az extension add --name ...`

Thanks for all the hard work producing the tools. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d7f5f91-5e89-9082-8c70-6431f0025f37
* Version Independent ID: 298daf64-db32-8b64-9a45-2c4c5e189522
* Content: [az monitor](https://docs.microsoft.com/en-us/cli/azure/ext/application-insights/monitor?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/application-insights/monitor.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/application-insights/monitor.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
@dbradish-microsoft could you please help with this?

**Comment by bbrandt** [comment]
The docs seem to say that the extension would install automagically, but this was not my experience.  I had to run:
```
az extension add --name application-insights
```

... as documented in my gist:
https://gist.github.com/bbrandt/2bd2d6a958fb6a8ccc3a6a18f74f8af7

**Comment by RakeshMohanMSFT** [comment]
Running this command [az monitor app-insights web-test list](https://learn.microsoft.com/en-us/cli/azure/monitor/app-insights/web-test?view=azure-cli-latest#az-monitor-app-insights-web-test-list) should try to automatically install the application insights extension if not already present.

**Comment by bbrandt** [comment]
@RakeshMohanMSFT Does "should try" mean that you have not confirmed the behavior? 

When I ran `az monitor app-insights component connect-webapp ...` it did not automatically install the extension for me.  Is the command you have list, [az monitor app-insights web-test list](https://learn.microsoft.com/en-us/cli/azure/monitor/app-insights/web-test?view=azure-cli-latest#az-monitor-app-insights-web-test-list), the only `monitor app-insights` that knows how to auto-install the extension?  If this is the case would this need to be listed as the install instructions since this may not be the `monitor app-insights` command that others may first run?

**Comment by RakeshMohanMSFT** [comment]
@tomstyles Yes, i did try the command. Sorry i forgot to attach the screenshot, it should ideally do that for every command dependent to that extension.

![image](https://user-images.githubusercontent.com/49954584/201399187-034dfcb6-f8ce-4e60-afa0-c1ed7dc69b0b.png)
