### ISSUE TITLE
upgrade helm procedure

### ISSUE THREAD

**Issue by TT554JJbgbg** [Azure/azure-cli-extensions#2490]
## Describe the bug

**Command Name**
`az connectedk8s connect
Extension Name: connectedk8s. Version: 0.2.6.`

**Errors:**
```
ValidationError: The current helm version is not supported for azure-arc onboarding. Please upgrade helm to a stable version and try again.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az connectedk8s connect --name {} --resource-group {}`

## Environment Summary
```
Linux-4.15.0-1095-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.12.0 *

Extensions:
connectedk8s 0.2.6
k8sconfiguration 0.1.8
ai-examples 0.2.3

```

**Comment by TT554JJbgbg** [comment]
az cloud shell using unstable version of helm.  update procedure?

**Comment by yonzhan** [comment]
connectedk8s

**Comment by navba-MSFT** [comment]
@TT554JJbgbg  Apologies for the late reply. Could you please try the below steps and let us know if you still face the issue ?

> az upgrade # Update the Azure CLI version
az extension update --name connectedk8s  # This will update the existing connectedk8s extension

Then you can try to run the [az connectedk8s connect](https://docs.microsoft.com/en-us/cli/azure/connectedk8s?view=azure-cli-latest#az-connectedk8s-connect) command and let us know if you run into any issues. 

Also this issue is open for quite sometime. Please let us know if you still need any assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@TT554JJbgbg I wanted to do quick follow-up to check if you had a chance to look at my above comment. This github issue is open for quite sometime. Please let us know if you need any further assistance on this. Awaiting your reply.
