### ISSUE TITLE
Azure Graph Query RateLimiting

### ISSUE THREAD

**Issue by Klaas-** [Azure/azure-cli-extensions#3325]
### Extension name (the extension in question)
resource-graph                     1.1.0

### Description of issue (in as much detail as possible)
Hi,
I am having an issue where I get errors like
```
{
    "error": {
        "code": "RateLimiting",
        "message": "Please provide below info when asking for support: timestamp = 2021-05-03T07:08:29.0524831Z, correlationId = .....",
        "details": [
            {
                "code": "RateLimiting",
                "message": "Client application has been throttled and should not attempt to repeat the request until an amount of time has elapsed. Please see https://aka.ms/resourcegraph-throttling for help."
            }
        ]
    }
}
```

It seems the azure resource graph query extension is not properly dealing with rate limiting. I would expect it to wait for the amount of seconds specified in x-ms-user-quota-resets-after and try again -- or something similar at the end of the day I would like a way to make sure my queries succeed -- it's okay if they take a little longer.

**Comment by yonzhan** [comment]
route to service team

**Comment by Klaas-** [comment]
Hi,
I would consider this as a bug unless you say it is by design that a query fails if it's being rate limited :) If this is by design I would need to code my own retry logic when using azure-cli.

**Comment by Klaas-** [comment]
it seems there was a similar problem with azure-cli aks https://github.com/Azure/azure-cli/issues/11891 - is this something that should be solved on the extension level or does this warrant a more general bug against azure-cli?

**Comment by snaheth** [comment]
Thanks @Klaas- and apologies for the late response. I'm a PM from the Azure Resource Graph team.

When using Resource Graph, there's two types of throttling/rate limiting you may encounter: [Azure Resource Manager Throttling](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling) and [Azure Resource Graph Throttling](https://docs.microsoft.com/en-us/azure/governance/resource-graph/concepts/guidance-for-throttled-requests). In your case, the error you shared indicates it's the latter type.

It's possible that you're hitting this error because of other clients (PowerShell, SDKs, Azure Portal) which are also consuming your limit quotas, and as a result, throttling you. Regarding your question about this behavior being by design -- that is correct -- A query will not return results if it's throttled.

@Klaas- I read through the AKS CLI issue you linked and this does sound like it would be a CLI change since waiting based on a header could be applied generically across multiple services.

**Comment by Klaas-** [comment]
@snaheth so will you raise an issue with az-cli or shall I raise one and reference this issue?

**Comment by snaheth** [comment]
@Klaas- Please go ahead and raise a new issue referring to this one and the AKS one you linked above.

Having a new issue would showcase more interest for having a quota header handler, so the CLI team is aware of it and can prioritize it eventually, pending their other existing commitments and priorities.
