### ISSUE TITLE
auotgenerated az managed-cassandra cmd error

### ISSUE THREAD

**Issue by elizabeth-hope** [Azure/azure-cli-extensions#3664]
## Describe the bug

**Command Name**
`az managed-cassandra cluster node-status
Extension Name: cosmosdb-preview. Version: 0.8.1.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'CassandraClustersOperations' object has no attribute 'fetch_node_status'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/elizabeth/.azure/cliextensions/cosmosdb-preview/azext_cosmosdb_preview/custom.py", line 548, in cli_cosmosdb_managed_cassandra_fetch_node_status
    return client.fetch_node_status(resource_group_name, cluster_name)
AttributeError: 'CassandraClustersOperations' object has no attribute 'fetch_node_status'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az managed-cassandra cluster node-status --resource-group {} --cluster-name {} --output {}`

## Environment Summary
```
Linux-5.4.0-1051-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.26.0 *

Extensions:
cosmosdb-preview 0.8.1
ai-examples 0.2.5
ssh 0.1.5

```

**Comment by yonzhan** [comment]
route to service team

**Comment by jsntcy** [comment]
@kavskalyan, please help take a look at this issue.
This issue was due to this [PR](https://github.com/Azure/azure-cli-extensions/commit/bd16344890df15128d27b42a9aa0490fa419fefa#diff-f397a5a646d89793922637118b6d27d0bec3aabb6ba72b3b04ce6c6b95621b63)(Track 2 migration).
[`client.fetch_node_status`](https://github.com/Azure/azure-cli-extensions/blob/bd16344890df15128d27b42a9aa0490fa419fefa/src/cosmosdb-preview/azext_cosmosdb_preview/custom.py#L548) should be changed to [`client.begin_fetch_node_status`](https://github.com/Azure/azure-cli-extensions/blob/bd16344890df15128d27b42a9aa0490fa419fefa/src/cosmosdb-preview/azext_cosmosdb_preview/vendored_sdks/azure_mgmt_cosmosdb/operations/_cassandra_clusters_operations.py#L788).

Please also refer to [track 2 SDK source code](https://github.com/Azure/azure-cli-extensions/tree/bd16344890df15128d27b42a9aa0490fa419fefa/src/cosmosdb-preview/azext_cosmosdb_preview/vendored_sdks/azure_mgmt_cosmosdb/operations) to check if there are any other places (Long running operation) that need change function name (add `begin_` prefix).

**Comment by AverageDesigner** [comment]
This issue is fixed with the PR https://github.com/Azure/azure-cli-extensions/pull/3723
