### ISSUE TITLE
feedback on -d

### ISSUE THREAD

**Issue by SteveDevOps** [Azure/azure-cli-extensions#533]
Can we get -d to accept/allow wildcards?  like -d INTEL_*  or -d *837*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e0abf1-d0b9-d886-c106-ae056daa47ec
* Version Independent ID: 7534d5aa-8270-49e5-21d6-e9456969a60e
* Content: [az iot hub](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/hub?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-hub-monitor-events)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by androidand** [comment]
Can you give an example on how to do this when we have an IoT hub set up with custom routes (going to event hubs and no messages ending up in $Default)?
I get no events at all with az iot hub monitor-events -n nameofhub. Been trying to set --consumer-group but then az terminates.

**Comment by c-ryan-k** [comment]
@SteveDevOps - this should be enabled as of 0.7.0:
![image](https://user-images.githubusercontent.com/13545962/59706333-1e999300-91b5-11e9-9405-9b0ea8af7e4b.png)

**Comment by yonzhan** [comment]
iot

**Comment by digimaun** [comment]
As @c-ryan-k mentioned, wildcards in the device id/ `-d` argument are supported as of `0.7.0`.

Then regarding monitor-events, there is a limitation where only the default eventhub endpoint can be monitored. This limitation is well known and on our radar. As a workaround, you could still keep a route to the default endpoint as each message is routed to all endpoints whose routing queries it matches. In other words, a message can be routed to multiple endpoints - [reference](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-d2c#routing-endpoints).

There has been a significant number of updates since this thread. I would recommend installing the latest and seeing if you run into the same "unknown" termination issue or issue setting a consumer group. Feel free to add a new issue to the [IoT extension repo](https://github.com/Azure/azure-iot-cli-extension).
