### ISSUE TITLE
`az containerapp up` attempts to register provider before validating args

### ISSUE THREAD

**Issue by TeamDman** [Azure/azure-cli-extensions#5610]
### Related command

`az containerapp up   --name mycontainerapp --image myacr.azurecr.io/food/meat:latest   --resource-group my-RGP   --environment managedEnvironment-waffles-9e1b   --ingress external   --target-port 80`

### Extension name (the extension in question)

containerapp

### Description of issue (in as much detail as possible)

The CLI attempts to register required providers before it validates the command arguments, leading to an authorization error instead of a resourcegroupnotfound error. 

The auth error:

```
{"error":{"code":"AuthorizationFailed","message":"The client 'beans@beans.com' with object id 'b-e-a-n-s' does not have authorization to perform action 'Microsoft.App/register/action' over scope '/subscriptions/d-e-e-z' or the scope is invalid. If access was recently granted, please refresh your credentials."}}
```

### Expected behaviour

User should receive a "resource group could not be found" error (hinting they might have the wrong subscription active)

### Observed behaviour

The command attempts to register providers before validating command args, leading to a permission error if the client doesn't have perms to register providers.

### Suggested fix

I believe swapping the order of these two lines would fix, but I'm not familiar enough to know for sure

https://github.com/Azure/azure-cli-extensions/blob/e335b8a97d85ac4cfe40accfa5c899c221a744c0/src/containerapp/azext_containerapp/custom.py#L2671-L2672

-----

**Comment by PramodValavala-MSFT** [comment]
@TeamDman This is the intended behavior since the resource provider would need to be registered before performing any of the follow up operations related to container apps. The error message does contain the subscription id (the scope), which indicates the subscription being used when running the command.

Also, the resource group is [just created](https://github.com/Azure/azure-cli-extensions/blob/e335b8a97d85ac4cfe40accfa5c899c221a744c0/src/containerapp/azext_containerapp/custom.py#L2704) if not present, so it not being present is not a possible error for this command.

**Comment by yonzhan** [comment]
route to CXP team

**Comment by TeamDman** [comment]
Makes sense, thanks for the quick reply!
