### ISSUE TITLE
az iot hub generate-sas-token returns error

### ISSUE THREAD

**Issue by davidahoward** [Azure/azure-cli-extensions#575]
the instructions for sas create token don't seem to work

az iot hub: 'generate-sas-token' is not in the 'az iot hub' command group. See 'az iot hub --help'.

It looks like I need to do this first - not obvious from docs
az extension add --name azure-cli-iot-ext

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e0abf1-d0b9-d886-c106-ae056daa47ec
* Version Independent ID: 7534d5aa-8270-49e5-21d6-e9456969a60e
* Content: [az iot hub](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/hub?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-hub-generate-sas-token)
* Content Source: [latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-cli-iot-ext/iot/hub.yml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw 
* Microsoft Alias: **routlaw**

**Comment by yonzhan** [comment]
iot

**Comment by yiyiguo** [comment]
@Azure/azure-iot-cli-triage

**Comment by digimaun** [comment]
@davidahoward - Hopefully by now your issue has been resolved. I just wanted to include a data point that `azure-cli-iot-ext` has been long since deprecated in favor of `azure-iot`. Going forward, if you still run into issues with `azure-iot`, you can post questions/problems [here](https://github.com/Azure/azure-iot-cli-extension) for dedicated support.

**Comment by SaurabhSharma-MSFT** [comment]
@davidahoward I believe this issue has been fixed and can be closed. Please let us know.
