### ISSUE TITLE
Live tests should be run periodically on published extensions.

### ISSUE THREAD

**Issue by adewaleo** [Azure/azure-cli-extensions#617]
### Description of issue (in as much detail as possible)

Extension Tests are currently run (in record mode) only when a PR is made to update an extension. 

However, live tests should be run on all published extensions periodically (at least during every CLI release) to increase the likelihood of detecting when an extension is broken by a CLI breaking change.

-----

**Comment by yonzhan** [comment]
add to S173

**Comment by haroldrandom** [comment]
Close as extension has been able to been published automatically and able to detect complete bug in developing stage.
Besides, the breakdown for unavailable extension is not common and the fix is easy to be done, so unnecessary to have a live test for extension for now unless @qwordy could help migrate the live test pipeline in Azure CLI to Azure CLI extensions.

**Comment by qwordy** [comment]
Good advice. I can extend the pipeline to support extension.
