### ISSUE TITLE
az iot hub device-twin update fails

### ISSUE THREAD

**Issue by ChristianBeier** [Azure/azure-cli-extensions#750]
## Describe the bug

**Command Name**
`az iot hub device-twin update --device-id abc --hub-name xyz --set properties.desired.testNum = 1234 
Extension Name: azure-cli-iot-ext. Version: 0.7.0.`

**Errors:**
```
pop from empty list
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 560, in execute
    raise ex
cli/core/commands/__init__.py, ln 618, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 611, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/arm.py, ln 804, in set_properties
    name, path = _get_name_path(key)
cli/core/commands/arm.py, ln 966, in _get_name_path
    return pathlist.pop(), pathlist
IndexError: pop from empty list
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub device-twin update --device-id {} --hub-name {} --set properties.desired.testNum = 1234`

## Expected Behavior
Update desired property testNum to 1234

## Environment Summary
```
Linux-4.4.0-18362-Microsoft-x86_64-with-debian-9.8
Python 3.6.5
Shell: bash

azure-cli 2.0.66
azure-cli-iot-ext 0.7.0

Extensions:
azure-cli-iot-ext 0.7.0

```
## Additional Context
Same behaviour under Windows Powershell with Azure CLI 2.0.59 and unknown azure-cli-iot-ext (version not shown respectively null). Proper examples for properties and not only tags would be recommended

**Comment by c-ryan-k** [comment]
Can you try the same command without spaces between `{property}={value}`?

We patched some other twin update code in 0.7.1 and this doesn't seem to repro anymore.

**Comment by yonzhan** [comment]
iot hub

**Comment by digimaun** [comment]
We've had a number of updates for this command since the issue was first submitted. The first recommendation is to update to the latest - the IoT extension is now called `azure-iot`.

Also usage of `--set` for `device-twin update` is deprecated ...you will want to use the `--desired` or `--tags` argument options.

Examples (bash json syntax) - 

- `az iot hub device-twin update -n {iothub_name} -d {device_id} --desired '{"conditions":{"temperature":{"warning":70, "critical":100}}}'`

- `az iot hub device-twin update -n {iothub_name} -d {device_id} --tags '{"country": "MyCountry"}'`
