### ISSUE TITLE
az pipelines list results in index out of range

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-cli-extensions#751]
## Describe the bug

**Command Name**
`az pipelines list
Extension Name: azure-devops. Version: 0.10.0.`

**Errors:**
```
list index out of range
Traceback (most recent call last):
pip-install-ygnynjtx\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 560, in execute
cli\core\commands\__init__.py, ln 618, in _run_jobs_serially
cli\core\commands\__init__.py, ln 609, in _run_job
azext_devops\dev\common\exception_handler.py, ln 26, in azure_devops_exception_handler
    reraise(*sys.exc_info())
Temp\pip-install-ygnynjtx\six\six.py, ln 693, in reraise
...
    return 'azdevops-cli:' + normalize_url_for_key(organization)
azext_devops\dev\common\_credentials.py, ln 85, in normalize_url_for_key
    organization_name = organization_name.split('/')[1]
IndexError: list index out of range
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az pipelines list --organization {} --project {}`

## Environment Summary
```
Windows-10-10.0.17134-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.66

Extensions:
azure-devops 0.10.0

```

**Comment by atbagga** [comment]
@MisinformedDNA You are probably giving the organization name as orgname instead of complete url like https://dev.azure.com/myorgname. 

This is a known issue and the fix to handle the error properly is in PR - https://github.com/Azure/azure-devops-cli-extension/pull/665.
Note that only error handling has been added, you will still need to give the complete url in case of configuring the organization or while passing it in each command. 

The fix will be released in version 0.11.0. ETA would be sometime next week.

Since this is a duplicate bug for - https://github.com/Azure/azure-devops-cli-extension/issues/538
it can be closed.
