### ISSUE TITLE
az pipeline list only shows build pipelines

### ISSUE THREAD

**Issue by marc-gmail-towersap** [Azure/azure-cli-extensions#973]
when I run  az pipelines list --org &lt;my org url&gt; --project &lt;myproject&gt;  i only see the build pipelines associated with that project.  I do NOT see any release pipelines at all.  
While I can run az pipelines release list and and can mine it's releaseDefinition, that only works if there is a release created in that release pipeline. If you created a release pipeline but never fired a build off, az pipelines release list won't find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a2123ca-5408-8f93-6f5c-93fe74684523
* Version Independent ID: 7a03fe73-da7f-9b5a-38e7-ef51d85d49fd
* Content: [az pipelines](https://docs.microsoft.com/en-us/cli/azure/ext/azure-devops/pipelines?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/ext/azure-devops/pipelines.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/ext/azure-devops/pipelines.yml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by atbagga** [comment]
@marc-gmail-towersap 

az pipeline list only shows build pipelines <-- This is expected since az pipelines commands work with Yaml pipelines. They will list builds and yaml multistage pipelines.

az pipelines release group commands work on the releases. 
1. If you are looking to list the release runs command is ```az pipelines release list```
2. If you are looking to list all the release definitions, the command is ```az pipelines release definition list```.

(2) will list all definitions regardless of a run is triggered on it or not. Is it what you are looking for?

**Comment by geverghe** [comment]
@marc-gmail-towersap - I am closing this issue. Feel free to re-open the issue in case the clarification is not clear. Would be awesome if you could open the issue in our repo - Azure/azure-devops-cli-extension directly in case you run into any issue with Pipelines commands.
